services:
  app:
    build: .
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - fastapi-volumes:/var/lib/fastapi/
    networks:
      - fastapi-networks
    restart: unless-stopped 
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: linkedin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root_linkedin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - fastapi-networks
    

volumes:
  fastapi-volumes:
  postgres-data:

networks:
  fastapi-networks:
    driver: bridge
